language: c

env:
    global:
        - OMP_NUM_THREADS=1

cache:
    - directories:
        - ${TRAVIS_BUILD_DIR}/depends/install
        - ${TRAVIS_BUILD_DIR}/depends/download
        - ${TRAVIS_BUILD_DIR}/depends/src

addons:
    apt:
        packages:
            - libopenmpi-dev
            - openmpi-bin
            - libgsl0-dev
            - libhdf5-dev

install:
    - sh bootstrap.sh
    - cp Options.mk.travis Options.mk
    - make

script:
    - pushd examples/dm-only
    - sh run.sh

